export default [
	{
		id: 1,
		name: "Monstera",
		latin: "Monstera Deliciosa",
		price: "120",
		description: "Lorem, ipsum dolor, sit amet consectetur adipisicing elit. Velit voluptatibus saepe suscipit repudiandae dolorem, voluptatem veniam, excepturi maiores qui magni praesentium voluptatum minus, tempora nemo quidem iure sit mollitia sint!",
		img: "Monstera.jpg",
	},
	{
		id: 2,
		name: "Succulent",
		latin: "Succulentus",
		price: "30",
		description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Vel consectetur quas blanditiis aliquam asperiores obcaecati iure praesentium in, nostrum, tempora totam qui labore dolore assumenda odit consequatur, est nihil quidem?",
		img: "Succulent.jpg",
	},
	{
		id: 3,
		name: "Hortensia",
		latin: "Hydrangea Macrophylla",
		price: "200",
		description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Pariatur, facilis impedit porro iure libero culpa quo repudiandae voluptatem suscipit possimus. Libero eum ea totam facere eveniet? Suscipit at quaerat hic!",
		img: "Hortensia.jpg",
	},
	{
		id: 4,
		name: "Spider Plant",
		latin: "Chlorophytum Comosum",
		price: "60",
		description: "Lorem ipsum, dolor sit, amet consectetur adipisicing elit. Consequatur cumque incidunt tempore doloremque ad ea, nemo, sapiente similique vitae. Vel sed architecto quisquam labore sint repellat porro placeat ad nobis.",
		img: "Spider_Plant.jpg",
	},
	{
		id: 5,
		name: "Orchid",
		latin: "Orchidaceae",
		price: "295",
		description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Praesentium, nesciunt assumenda iusto accusamus officia eum dicta, ratione, culpa rem, laboriosam est? Provident, minima magnam. Consequuntur reiciendis ex provident nostrum, omnis.",
		img: "Orchid.jpg",
	},
	{
		id: 6,
		name: "Weeping Fig",
		latin: "Ficus Benjamina",
		price: "100",
		description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Tenetur quis excepturi, mollitia eum natus magni doloribus officia similique ex! Cupiditate, laboriosam voluptate aperiam reiciendis, facilis accusantium quod exercitationem labore modi!",
		img: "Weeping_Fig.jpg",
	},
	{
		id: 7,
		name: "Money Plant",
		latin: "Pilea Peperomioides",
		price: "75",
		description: "Lorem ipsum dolor sit amet consectetur adipisicing, elit. Non reiciendis earum cupiditate, tempora odio perferendis consectetur, possimus ipsum officiis dolorum fugiat libero deleniti vero, quam, esse. Dolore libero magnam, ab.",
		img: "Money_Plant.jpg",
	},
	{
		id: 8,
		name: "Lucky Bamboo",
		latin: "Dracaena Sanderiana",
		price: "88",
		description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime eaque amet, nulla porro voluptatibus tenetur iure mollitia asperiores numquam quasi optio facere at vero? Voluptatum nulla eligendi modi et fugiat.",
		img: "Lucky_Bamboo.jpg",
	},
	{
		id: 9,
		name: "Lavender",
		latin: "Lavandula",
		price: "60",
		description: "Lorem ipsum dolor sit amet consectetur adipisicing, elit. Aliquid, autem non temporibus quis officia illum animi odio fugiat suscipit, atque laborum assumenda quos eos esse doloremque nostrum, voluptatem voluptatum cupiditate.",
		img: "Lavender.jpg",
	},
	{
		id: 10,
		name: "Star Jasmine",
		latin: "Trachelospermum Jasminoides",
		price: "450",
		description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod corrupti eligendi impedit nobis error, veniam sed excepturi aspernatur nam, maiores laudantium explicabo aliquam minima sequi ad molestias sit deleniti a?",
		img: "Star_Jasmine.jpg",
	},
	{
		id: 11,
		name: "Aloe Vera",
		latin: "Aloe Barbadensis",
		price: "75",
		description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi cumque amet nam natus libero tempore iusto dicta officiis pariatur dolore rem, aperiam vel doloribus excepturi illo ducimus explicabo doloremque odio.",
		img: "Aloe_Vera.jpg",
	},
	{
		id: 12,
		name: "Passion Flower",
		latin: "Passiflora Incarnata",
		price: "220",
		description: "Lorem ipsum dolor, sit amet, consectetur adipisicing elit. Nulla aspernatur iure eveniet, eius perferendis consectetur tempore atque nam quis sapiente. Perferendis voluptatum, exercitationem porro modi hic, facere magnam id ipsam.",
		img: "Passion_Flower.jpg",
	},
]
